### ISSUE TITLE
Define environments for publish

### ISSUE THREAD

**Issue by dyoder** [pandastrike/haiku9#31]
Example:

```yaml
s3:
  domain: pandastrike.com

  region: us-west-2

  web:
    index: index
    error: 404

  environments:
    staging:
      hostnames:
        - staging
        - test
      cache:
        expires: 60 # 1 minute
    production:
      cname: true
      hostnames:
      - www
      cache:
          expires: 1800 # 30 minutes
```
